### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by plamer777** [RadiBytes/python-whatsapp-bot#5]
Hi there! I've been trying to send a Whatsapp message by using 'send_message' method but without success. There's always the error of requests package I placed in title of the issue. I tried to update requests and change python interpreter from 3.12 to 3.11 but nothing helps to fix the bug.
Is there any opinion what's reason of the issue?

**Comment by RadiBytes** [comment]
This is usually due to network issues. Try connecting with a different provider

**Comment by RadiBytes** [comment]
This is usually due to network issues. Try connecting with a different provider
